# Generated by Django 5.0.6 on 2024-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("lamp", "Lamp"),
                            ("chandelier", "Chandelier"),
                            ("washing_machine", "Washing Machine"),
                            ("tv", "TV"),
                            ("dishwasher", "Dishwasher"),
                            ("fridge", "Fridge"),
                            ("microwave", "Microwave"),
                            ("air_conditioner", "Air Conditioner"),
                            ("heater", "Heater"),
                            ("computer", "Computer"),
                            ("speaker", "Speaker"),
                            ("blinds", "Blinds"),
                            ("plug", "Plug"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("is_on", models.BooleanField(default=False)),
                ("energy_consumption", models.FloatField(default=0.0)),
            ],
        ),
    ]
